CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    display_name    VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(60)  NOT NULL,
    color           VARCHAR(7)   NOT NULL DEFAULT '#9CA3AF',
    type            VARCHAR(10)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tag_name_type UNIQUE (name, type)
);

CREATE TABLE transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section             VARCHAR(20)  NOT NULL,
    type                VARCHAR(10)  NOT NULL,
    amount              BIGINT       NOT NULL,
    occurred_at         TIMESTAMP    NOT NULL,
    memo                VARCHAR(500),
    created_by_user_id  BIGINT       NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tx_user      FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT ck_tx_amount    CHECK (amount > 0)
);

CREATE INDEX idx_tx_occurred_at ON transactions (occurred_at DESC);
CREATE INDEX idx_tx_section_occurred ON transactions (section, occurred_at DESC);

CREATE TABLE transaction_tags (
    transaction_id BIGINT NOT NULL,
    tag_id         BIGINT NOT NULL,
    PRIMARY KEY (transaction_id, tag_id),
    CONSTRAINT fk_tt_tx   FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
    CONSTRAINT fk_tt_tag  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE RESTRICT
);

CREATE TABLE recurring_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    section             VARCHAR(20)  NOT NULL,
    type                VARCHAR(10)  NOT NULL,
    amount              BIGINT       NOT NULL,
    day_of_month        SMALLINT,
    memo                VARCHAR(500),
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by_user_id  BIGINT       NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rt_user FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT ck_rt_amount CHECK (amount > 0),
    CONSTRAINT ck_rt_dom CHECK (day_of_month IS NULL OR (day_of_month BETWEEN 1 AND 31))
);

CREATE TABLE recurring_transaction_tags (
    recurring_transaction_id BIGINT NOT NULL,
    tag_id                   BIGINT NOT NULL,
    PRIMARY KEY (recurring_transaction_id, tag_id),
    CONSTRAINT fk_rtt_rt  FOREIGN KEY (recurring_transaction_id) REFERENCES recurring_transactions(id) ON DELETE CASCADE,
    CONSTRAINT fk_rtt_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE RESTRICT
);

CREATE TABLE initial_balances (
    section     VARCHAR(20) PRIMARY KEY,
    amount      BIGINT      NOT NULL,
    as_of_date  DATE        NOT NULL,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO initial_balances (section, amount, as_of_date) VALUES
    ('SHARED',  0, CURRENT_DATE),
    ('HUSBAND', 0, CURRENT_DATE),
    ('WIFE',    0, CURRENT_DATE);
